FROM node:14

WORKDIR /app

# Copy only the server.js file
COPY server.js ./

# Install only the necessary dependencies directly
RUN npm install express socket.io axios

EXPOSE 3001

CMD ["node", "server.js"]
